{% set version = "0.3.9" %}

package:
  name: freezegun
  version: {{ version }}

source:
  fn: freezegun-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/f/freezegun/freezegun-{{ version }}.tar.gz
  sha256: 783ccccd7f60968bfe49ad9e114c18ea2b63831faaaf61c1f1f71ddfde1c0eee

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six
    - python-dateutil >=1.0,!=2.0  # [not py3k]
    - python-dateutil >=2.0  # [py3k]

test:
  imports:
    - freezegun

about:
  home: https://github.com/spulec/freezegun
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Let your Python tests travel through time.'

extra:
  recipe-maintainers:
    - ocefpaf
