package:
  name: cookiecutter-django
  version: "1.9.9.5"

source:
  git_rev: 1.9.9-05
  git_url: https://github.com/pydanny/cookiecutter-django.git

Build:
  number: 1

  
requirements:
  build:
    - python
    - setuptools
    - git

  run:
    - python
    - cookiecutter
    - flake8  

test:
  requires:
    - cookiecutter


about:
  home: https://github.com/pydanny/cookiecutter-django/releases
  license: BSD
  summary: Cookiecutter Django is a framework for jumpstarting production-ready Django projects quickly. 

