{% set name = "channels" %}
{% set version = "1.1.6" %}
{% set hash_type = "sha256" %}
{% set hash_value = "44ab9a1f610ecc9ac25d5f90e7a44f49b18de28a05a26fe34e935af257f1eefe" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - django >=1.8
    - asgiref >=1.1
    - daphne >=1.3
  run:
    - python
    - django >=1.8
    - asgiref >=1.1
    - daphne >=1.3

test:
  imports:
    - channels
    - channels.binding
    - channels.delay
    - channels.delay.management
    - channels.delay.management.commands
    - channels.delay.migrations
    - channels.generic
    - channels.management
    - channels.management.commands
    - channels.security
    - channels.test
    - channels.tests

about:
  home: http://github.com/django/channels
  license: BSD 3-clause 
  license_family: BSD
  license_file: LICENSE
  summary: Brings event-driven capabilities to Django with a channel system. Django 1.8 and up only.
  description: "Django Channels\n===============\n\n.. image:: https://api.travis-ci.org/django/channels.svg\n    :target: https://travis-ci.org/django/channels\n\n.. image:: https://readthedocs.org/projects/channels/badge/?version=latest\n\
    \    :target: https://channels.readthedocs.io/en/latest/?badge=latest\n\n.. image:: https://img.shields.io/pypi/v/channels.svg\n    :target: https://pypi.python.org/pypi/channels\n\n.. image:: https://img.shields.io/pypi/l/channels.svg\n\
    \    :target: https://pypi.python.org/pypi/channels\n\nChannels loads into Django as a pluggable app to bring WebSocket, long-poll HTTP,\ntask offloading and other asynchrony support to your code, using\
    \ familiar Django\ndesign patterns and a flexible underlying framework that lets you not only\ncustomize behaviours but also write support for your own protocols and needs.\n\nDocumentation, installation\
    \ and getting started instructions are at\nhttps://channels.readthedocs.io\n\nChannels is an official Django Project and as such has a deprecation policy.\nDetails about what's deprecated or pending\
    \ deprecation for each release is in\nthe `release notes <http://channels.readthedocs.io/en/latest/releases/index.html>`_.\n\nSupport can be obtained either here via issues, or in the ``#django-channels``\n\
    channel on Freenode.\n\nYou can install channels from PyPI as the ``channels`` package.\nYou'll likely also want to install ``asgi_redis`` or ``asgi_rabbitmq``\nto provide the Redis/RabbitMQ channel\
    \ layer correspondingly.\nSee our `installation <https://channels.readthedocs.io/en/latest/installation.html>`_\nand `getting started <https://channels.readthedocs.io/en/latest/getting-started.html>`_\
    \ docs for more.\n\nDependencies\n------------\n\nAll Channels projects currently support Python 2.7, 3.4 and 3.5. `channels` supports all released\nDjango versions, namely 1.8-1.10.\n\n\nContributing\n\
    ------------\n\nTo learn more about contributing, please `read our contributing docs <https://channels.readthedocs.io/en/latest/contributing.html>`_.\n\n\nMaintenance and Security\n------------------------\n\
    \nTo report security issues, please contact security@djangoproject.com. For GPG\nsignatures and more security process information, see\nhttps://docs.djangoproject.com/en/dev/internals/security/.\n\n\
    To report bugs or request new features, please open a new GitHub issue. For\nlarger discussions, please post to the\n`django-developers mailing list <https://groups.google.com/d/forum/django-developers>`_.\n\
    \nDjango Core Shepherd: Andrew Godwin <andrew@aeracode.org>\n\nMaintenance team:\n\n* Andrew Godwin <andrew@aeracode.org>\n* Steven Davidson\n* Jeremy Spencer\n\nIf you are interested in joining the\
    \ maintenance team, please\n`read more about contributing <https://channels.readthedocs.io/en/latest/contributing.html>`_\nand get in touch!\n\n\nOther Projects\n--------------\n\nThe Channels project\
    \ is made up of several packages; the others are:\n\n* `Daphne <https://github.com/django/daphne/>`_, the HTTP and Websocket termination server\n* `asgiref <https://github.com/django/asgiref/>`_, the\
    \ base ASGI library/memory backend\n* `asgi_redis <https://github.com/django/asgi_redis/>`_, the Redis channel backend\n* `asgi_rabbitmq <https://github.com/proofit404/asgi_rabbitmq/>`_, the RabbitMQ\
    \ channel backend\n* `asgi_ipc <https://github.com/django/asgi_ipc/>`_, the POSIX IPC channel backend\n"
  doc_url: https://channels.readthedocs.io/en/stable/
  dev_url: http://github.com/django/channels

extra:
  recipe-maintainers: ''
