{% set version = "0.4.3" %}
{% set gh_org = "audreyr" %}
{% set gh_repo = "binaryornot" %}


package:
  name: {{ gh_repo }}
  version: {{ version }}

source:
  fn: {{ gh_repo }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ gh_repo[0] }}/{{ gh_repo }}/{{ gh_repo }}-{{ version }}.tar.gz
  sha256: d359566c1744526be6ea47e56bbc6f506a76cabdd49c09f6847520594f1b309e

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - chardet

test:
  source_files:
    - .
  requires:
    - coverage
    - hypothesis
    - python
    - setuptools
  commands:
    - python setup.py test

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Ultra-lightweight pure Python package to check if a file is binary or text.
  doc_url: https://binaryornot.readthedocs.io/en/latest/
  dev_url: https://github.com/audreyr/binaryornot

extra:
  recipe-maintainers:
    - bollwyvl
