{% set name = "txaio" %}
{% set version = "2.8.0" %}
{% set sha256 = "8029d956591107ff9a2221d2a288fdd3718713a6991f59b97359d3d4f4b7b564" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - txaio

about:
  home: https://github.com/crossbario/txaio
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Compatibility API between asyncio/Twisted/Trollius'
  dev_url: https://github.com/crossbario/txaio
  doc_url: http://txaio.readthedocs.io/

extra:
  recipe-maintainers:
    - synapticarbors
